###การบ้าน CRUD
GET http://localhost:3000/api/roles

###
GET http://localhost:3000/api/roles/1

###
GET http://localhost:3000/api/roles/99

###
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "name": "TestRoles03"
}

###
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "name": "TestRoles0200009898989898564645"
}

###
PATCH http://localhost:3000/api/roles/6
Content-Type: application/json

{
    "name": "TestRoles06"
}

###
PATCH http://localhost:3000/api/roles/10
Content-Type: application/json

{
    "name": "TestRoles01"
}

###
PATCH http://localhost:3000/api/roles/1
Content-Type: application/json

{
    "name": "TestRoles0111111111111111111111111111111111111111111"
}

###
DELETE  http://localhost:3000/api/roles/6
